wecare-backend/wecare/build.gradle, wecare-backend/wecare/src/main/java/com/example/wecare/config/CorsConfig.java, wecare-backend/wecare/src/main/java/com/example/wecare/config/SwaggerConfig.java, wecare-backend/wecare/src/main/resources/application.yml
=> setting: Spring Swagger, Cors Configuration

wecare-backend/wecare/src/main/java/com/example/wecare/config/SecurityConfig.java
```
26     //.anyRequest().authenticated()
27     .anyRequest().permitAll() // 모든 요청 허용
```
개발 중 SpringSecurity가 모든 요청을 허용하도록 수정
=> feat: 모든 경로 접근 허용을 위한 SecurityConfig 업데이트

wecare-backend/wecare/src/main/java/com/example/wecare/auth/controller/AuthController.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/dto/LoginRequest.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/dto/SignUpRequest.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/jwt/JwtTokenProvider.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/service/AuthService.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/service/CustomUserDetailsService.java, wecare-backend/wecare/src/main/java/com/example/wecare/exception/GlobalExceptionHandler.java, wecare-backend/wecare/src/main/java/com/example/wecare/member/domain/Member.java, wecare-backend/wecare/src/main/java/com/example/wecare/member/repository/MemberRepository.java, wecare-backend/wecare/src/test/java/com/example/wecare/auth/controller/AuthControllerTest.java, wecare-backend/wecare/src/test/java/com/example/wecare/auth/service/AuthServiceTest.java
- 회원가입 시 전호번호 대신 memberId 받도록 수정 (전화번호 삭제)
- 테스트 코드 수정
=> Feature/회원가입 로직 업데이트 (memberId 기반 로그인)

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- 상대경로 잘못 입력으로 인한 오류 수정 (3차 테스트 진행 중)
- NGINX + CERTBOT으로 HTTPS 적용 완료
- www.mobidic.shop 도메인 적용 예정 (과거 프로젝트에 쓰던 기한 많이 남는 도메인 사용)
=> [Release] 3차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
Reverts WeCare-DeepDive/wecare-app#18
- Swagger 의존성 관련 버전 명시 필요
=> Revert "[Release] 3차 Release 및 CI/CD 테스트"

wecare-backend/wecare/build.gradle
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- NGINX + CERTBOT으로 HTTPS 적용 완료
- www.mobidic.shop 도메인 적용 예정 (과거 프로젝트에 쓰던 기한 많이 남는 도메인 사용)
=> [Release] 4차 Release 및 CI/CD 테스트

wecare-backend/wecare/build.gradle
Reverts WeCare-DeepDive/wecare-app#18
- 코드 수정내용 누락;;
=> Revert "[Release] 4차 Release 및 CI/CD 테스트"

wecare-backend/wecare/build.gradle
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- NGINX + CERTBOT으로 HTTPS 적용 완료
- www.mobidic.shop 도메인 적용 예정 (과거 프로젝트에 쓰던 …
=> [Release] 5차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml, wecare-backend/wecare/build.gradle
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- NGINX + CERTBOT으로 HTTPS 적용 완료
- …
=> [Release] 6차 Release 및 CI/CD 테스트

wecare-backend/wecare/src/main/resources/application.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 8차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 11차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml, wecare-backend/wecare/src/main/resources/application.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 12차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 15차 Release 및 CI/CD 테스트

wecare-backend/wecare/src/main/resources/application-test.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 17차 Release 및 CI/CD 테스트

wecare-backend/wecare/src/main/resources/application-test.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 20차 Release 및 CI/CD 테스트

wecare-backend/wecare/src/main/resources/application-test.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 22차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 23차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 25차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 26차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 27차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 28차 Release 및 CI/CD 테스트

.github/workflows/deploy.yml
- JWT 인증 방식 구현
- 로그아웃 시 토큰 폐기
- 테스트 코드 작성
- 테스트 코드 수정
- Redis 관련 …
=> [Release] 29차 Release 및 CI/CD 테스트

wecare-backend/wecare/build.gradle, wecare-backend/wecare/src/main/java/com/example/wecare/auth/dto/LoginRequest.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/dto/LoginResponse.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/dto/SignUpRequest.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/service/AuthService.java, wecare-backend/wecare/src/main/java/com/example/wecare/auth/service/CustomUserDetailsService.java, wecare-backend/wecare/src/main/java/com/example/wecare/member/domain/Member.java, wecare-backend/wecare/src/main/java/com/example/wecare/member/repository/MemberRepository.java
refactor: memberId -> username 변경
- members 테이블의 memberId는 pk와 혼동의 여지 있으므로 변경
fix: auditing 관련 코드 수정
- createdAt, updatedAt에 insertable=false 옵션 추가
=> [Refactor] members.memberId => members.username refactoring

wecare-backend/wecare/src/main/java/com/example/wecare/config/CorsConfig.java, wecare-backend/wecare/src/main/java/com/example/wecare/config/SwaggerConfig.java
- https://www.mobidic.shop URL로 Swagger 테스트 가능하도록 config
=> config: Swagger 테스트 서버 명시

.github/workflows/test-main.yml
- https://www.mobidic.shop URL을 통해 Swagger로 테스트 가능
=> [Config] Swagger 테스트 서버 명시

wecare-frontend/wecare-fe/src/components/Calendar/Calendar.jsx, wecare-frontend/wecare-fe/src/components/common/Header.jsx, wecare-frontend/wecare-fe/src/navigation/BottomNavigation.jsx, wecare-frontend/wecare-fe/src/screen/Home/HomeScreen.jsx, wecare-frontend/wecare-fe/src/styles/theme.js
1. 홈 화면 Depth 1 화면 디자인
2. 캘린더 디자인 수정
3. Theme Color 추가
=> design: 홈 Depth 1 화면 디자인

wecare-frontend/wecare-fe/src/components/modal/RoutineModal.jsx, wecare-frontend/wecare-fe/src/providers/apiProvider.js, wecare-frontend/wecare-fe/src/screen/Auth/LoginScreen.jsx, wecare-frontend/wecare-fe/src/screen/Routine/InvitationScreen.jsx, wecare-frontend/wecare-fe/src/screen/Routine/api/inviteApi.js, wecare-frontend/wecare-fe/src/screen/Routine/components/NonInviteFamilyScreen.jsx, wecare-frontend/wecare-fe/src/screen/Routine/store/inviteStore.js
> 가족 추가 및 연결 기능을 위한 API 연동, 상태 관리 로직, 가족 연결 폼 화면을 구현하였습니다.
> '하루' 부분의 코어 화면 제작 진행중
1. 유저 관련 API 수정
- 유저 정보 구조 일부 수정 또는 엔드포인트 호출 방식 조정
2. 가족 연결 API 추가
- 초대코드 기반 가족 연결 요청 처리 추가
- 연결 성공 시 연결된 상태로 상태 업데이트 처리
3. 가족 연결 상태 관리 추가 (Zustand)
- `inviteStore` 생성
- 가족 연결 요청, 초대코드 불러오기, 연결 상태 저장 등 포함
4. 폼 화면 구성
- 초대코드 입력 및 관계 선택 화면 추가
- 입력 유효성 검사 및 연결 요청 처리 기능 포함
5. 연결 상태에 따른 라우팅 처리
- 이미 가족 연결이 되어있는 경우, 해당 화면을 건너뛰고 다음 화면으로 이동 처리
- 현재는 UI/UX의 전체 흐름을 설계 중이며, 이후 디자인 고도화 예정
- 일부 비즈니스 로직은 백엔드 협의에 따라 추가 조정될 수 있음
=> feat: 가족 추가 기능 및 연결 화면 구현

wecare-backend/wecare/src/main/java/com/example/wecare/routine/controller/RoutineController.java
- GET /api/routines/{dependentId} -> GET /api/routines/{dependentId}/repeats
=> [Fix] 루틴 중복 엔드포인트 수정

wecare-backend/wecare/src/main/java/com/example/wecare/connection/controller/ConnectionController.java, wecare-backend/wecare/src/main/java/com/example/wecare/connection/dto/ConnectionDetailDto.java, wecare-backend/wecare/src/main/java/com/example/wecare/connection/dto/UpdateRelationshipRequest.java, wecare-backend/wecare/src/main/java/com/example/wecare/connection/service/ConnectionService.java
- 상대방 사용자의 Name 필드 추가
- fix: UpdateRelationshipRequest DTO 명 변경
=> [Feature] 내 연결 세부 정보 목록 조회 API 추가

wecare-frontend/wecare-fe/src/screen/My/MyPageScreen.jsx, wecare-frontend/wecare-fe/src/styles/theme.js
=> design: mypage 화면 1 depth
